-- 코드를 입력하세요
SELECT T2.PRODUCT_CODE
     , SUM(T1.SALES_AMOUNT) * T2.PRICE AS SALES
FROM   OFFLINE_SALE T1
INNER 
JOIN   PRODUCT T2
ON     T2.PRODUCT_ID = T1.PRODUCT_ID
GROUP BY T2.PRODUCT_CODE, T2.PRICE
ORDER BY 2 DESC, 1 ASC;