-- 코드를 입력하세요
SELECT MCDP_CD             AS 진료과코드
     , COUNT(MCDP_CD)      AS "5월예약건수"
FROM   APPOINTMENT
WHERE  1 = 1 
AND    TO_CHAR(APNT_YMD, 'YYYY-MM-DD') >= '2022-05-01'
AND    TO_CHAR(APNT_YMD, 'YYYY-MM-DD') < '2022-06-01'
GROUP BY MCDP_CD
ORDER BY 2, 1;