-- 코드를 입력하세요
SELECT T1.BOOK_ID
     , T2.AUTHOR_NAME
     , TO_CHAR(T1.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM   BOOK T1
INNER
JOIN   AUTHOR T2
ON     T2.AUTHOR_ID = T1.AUTHOR_ID
AND    T1.CATEGORY = '경제'
ORDER BY 3;