-- 코드를 입력하세요
SELECT INS.ANIMAL_ID
      , INS.NAME
FROM   ANIMAL_INS INS
INNER
JOIN   ANIMAL_OUTS OUTS
ON     OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE  1 = 1
AND    INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME;